import { stringify } from 'yaml';
import { projectEditorConfigSnippet } from './projectEditorConfig.js';

const TIER_FOLDER_NAMES = [
  'atoms',
  'molecules',
  'organisms',
  'recipes',
  'views',
  'apps',
  'sockets',
  'plugs',
  'ui',
] as const;

const VIEW_EXTENSION_GLOBS = ['**/*.svelte', '**/*.tsx', '**/*.jsx', '**/*.vue'];

const EXTRA_VIEW_CANDIDATES = [
  'ui/components',
  'components',
  'ui',
  'presentation',
  'widgets',
] as const;

export type ProjectStack = 'svelte' | 'react' | 'vue' | 'generic';

export type ConfigPresetId = 'detected' | 'minimal' | 'svelte' | 'react' | 'vue';

export type ProjectAnalysis = {
  /** Absolute filesystem path to project root. */
  rootPath: string;
  stack: ProjectStack;
  srcRoot: string;
  tiersFound: string[];
  importAliases: Record<string, string>;
  extraViewPaths: string[];
  ignoreGlobs: string[];
  signals: string[];
};

export type ConfigDraft = {
  preset: ConfigPresetId;
  analysis: ProjectAnalysis;
  yaml: string;
  summary: string;
};

export function buildConfigDraft(analysis: ProjectAnalysis, preset: ConfigPresetId): ConfigDraft {
  const body = preset === 'minimal' ? minimalConfigBody(analysis) : detectedConfigBody(analysis, preset);
  const header = buildHeader(analysis, preset);
  const yaml = `${header}\n${stringify(body, { lineWidth: 0 }).trimEnd()}\n`;
  return {
    preset,
    analysis,
    yaml,
    summary: describeDraft(analysis, preset),
  };
}

function buildHeader(analysis: ProjectAnalysis, preset: ConfigPresetId): string {
  const lines = [
    '# CLAD audit config — generated by the CLAD Audit extension.',
    '# Docs: https://github.com/Underwood-Inc/clad-audit#copy-paste-configs',
    `# Preset: ${preset} · stack: ${analysis.stack} · srcRoot: ${analysis.srcRoot}`,
  ];
  for (const signal of analysis.signals) {
    lines.push(`# · ${signal}`);
  }
  lines.push('# Review importAliases and ignoreGlobs before committing.');
  lines.push(projectEditorConfigSnippet().trimEnd());
  return lines.join('\n');
}

function describeDraft(analysis: ProjectAnalysis, preset: ConfigPresetId): string {
  const aliasCount = Object.keys(
    preset === 'minimal' ? {} : analysis.importAliases,
  ).length;
  return [
    `Preset: ${preset}`,
    `Stack: ${analysis.stack}`,
    `srcRoot: ${analysis.srcRoot}`,
    `Tiers found: ${analysis.tiersFound.join(', ') || '(none — check srcRoot)'}`,
    `Import aliases: ${aliasCount}`,
    analysis.extraViewPaths.length
      ? `Extra view paths: ${analysis.extraViewPaths.join(', ')}`
      : 'Extra view paths: (none)',
  ].join('\n');
}

function minimalConfigBody(analysis: ProjectAnalysis): Record<string, unknown> {
  return {
    srcRoot: analysis.srcRoot,
    ignoreGlobs: baseIgnoreGlobs('generic'),
    analysis: {
      defaultDepth: 'standard',
    },
  };
}

function detectedConfigBody(
  analysis: ProjectAnalysis,
  preset: ConfigPresetId,
): Record<string, unknown> {
  const stack = preset === 'detected' ? analysis.stack : preset;
  const doc: Record<string, unknown> = {
    srcRoot: analysis.srcRoot,
  };

  if (Object.keys(analysis.importAliases).length > 0) {
    doc.importAliases = sortRecord(analysis.importAliases);
  }

  doc.ignoreGlobs = stackIgnoreGlobs(stack, analysis);

  doc.analysis = {
    defaultDepth: 'standard',
    useTsMorph: true,
  };

  if (stack === 'svelte') {
    doc.svelteProps = {
      enabled: true,
      maxProps: 4,
      severity: 'warning',
    };
  }

  const views: Record<string, unknown> = {};
  if (stack === 'react') {
    views.extensions = ['.tsx', '.jsx', '.vue'];
  } else if (stack === 'vue') {
    views.extensions = ['.vue', '.tsx', '.jsx'];
  }
  if (analysis.extraViewPaths.length > 0) {
    views.extraViewPaths = [...analysis.extraViewPaths];
  }
  if (Object.keys(views).length > 0) {
    doc.views = views;
  }

  return doc;
}

function stackIgnoreGlobs(stack: ProjectStack, analysis: ProjectAnalysis): string[] {
  const globs = new Set(baseIgnoreGlobs(stack));
  for (const g of analysis.ignoreGlobs) globs.add(g);
  return [...globs];
}

function baseIgnoreGlobs(stack: ProjectStack): string[] {
  const common = ['**/node_modules/**', '**/dist/**', '**/*.d.ts', '**/coverage/**', '**/.git/**'];
  if (stack === 'svelte') {
    return [...common, '**/.svelte-kit/**'];
  }
  if (stack === 'react') {
    return [...common, '**/.next/**', '**/build/**'];
  }
  if (stack === 'vue') {
    return [...common, '**/.nuxt/**', '**/.output/**'];
  }
  return common;
}

function sortRecord(input: Record<string, string>): Record<string, string> {
  return Object.fromEntries(Object.entries(input).sort(([a], [b]) => a.localeCompare(b)));
}

export { TIER_FOLDER_NAMES, EXTRA_VIEW_CANDIDATES, VIEW_EXTENSION_GLOBS };
